spring:
    application:
        name: digitalsky
    datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/digitalsky?useSSL=false
        username: digitalsky
        password: digitalsky
        driverClassName: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        ddl-auto: none
      properties:
        javax:
          persistence:
            validation:
              mode: none
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    servlet:
      multipart:
        max-file-size: 50MB

    logging:
        file: logs/dev_app.log
        level:
            org: DEBUG
    data:
      mongodb:
        host: ${MONGO_DB_HOST:localhost}
        port: ${MONGO_DB_PORT:27017}
        database: digitalsky
flyway:
  enabled: true
  url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/digitalsky?useSSL=false
  user: digitalsky
  password: digitalsky
  locations: classpath:/db/migration

server:
  port: 9000
  http-port: 9000
