CREATE TABLE DS_ORGANIZATION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(500),
    EMAIL VARCHAR(255),
    MOBILE_NUMBER VARCHAR(15),
    CONTACT_NUMBER VARCHAR(15),
    COUNTRY VARCHAR(50)
);
