CREATE TABLE DS_PERSON_ADDRESS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    ADDRESS_ID INT,
    TYPE VARCHAR(10),
    FOREIGN KEY (USER_ID) REFERENCES DS_USER(ID)
    FOREIGN KEY (ADDRESS_ID) REFERENCES DS_ADDRESS(ID)
);
