CREATE TABLE DS_ADDRESS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LINE_ONE VARCHAR(100),
    LINE_TWO VARCHAR(100),
    TOWN_OR_CITY VARCHAR(50),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    PIN_CODE VARCHAR(10)
);