CREATE TABLE DS_PERSON (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(500),
    LAST_NAME VARCHAR(500),
    EMAIL VARCHAR(255),
    MOBILE_NUMBER VARCHAR(15),
    AGE_IN_MONTHS INT,
    COUNTRY VARCHAR(50)
);