CREATE TABLE DS_INDIVIDUAL_OPERATOR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RESOURCE_OWNER_ID INT,
    PERSON_ID INT,
    STATUS VARCHAR(10),
    FOREIGN KEY (PERSON_ID) REFERENCES DS_PERSON(ID)
);
